<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Posisi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Posisi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'posisi/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'posisi/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'posisi/index.html';
            $config['first_url'] = base_url() . 'posisi/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Posisi_model->total_rows($q);
        $posisi = $this->Posisi_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'posisi_data' => $posisi,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','posisi/tbl_posisi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Posisi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_posisi' => $row->id_posisi,
		'nama_posisi' => $row->nama_posisi,
	    );
            $this->template->load('template','posisi/tbl_posisi_read', $data);       
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('posisi/create_action'),
	    'id_posisi' => set_value('id_posisi'),
	    'nama_posisi' => set_value('nama_posisi'),
	);
        $this->template->load('template','posisi/tbl_posisi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_posisi' => $this->input->post('nama_posisi',TRUE),
	    );

            $this->Posisi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('posisi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Posisi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('posisi/update_action'),
		'id_posisi' => set_value('id_posisi', $row->id_posisi),
		'nama_posisi' => set_value('nama_posisi', $row->nama_posisi),
	    );
            $this->template->load('template','posisi/tbl_posisi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_posisi', TRUE));
        } else {
            $data = array(
		'nama_posisi' => $this->input->post('nama_posisi',TRUE),
	    );

            $this->Posisi_model->update($this->input->post('id_posisi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('posisi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Posisi_model->get_by_id($id);

        if ($row) {
            $this->Posisi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('posisi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_posisi', 'nama posisi', 'trim|required');

	$this->form_validation->set_rules('id_posisi', 'id_posisi', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Posisi.php */
/* Location: ./application/controllers/Posisi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-08 09:12:16 */
/* http://harviacode.com */