<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_model extends CI_Model
{

    public $table = 'tbl_fakultas';
    public $id = 'id_fakultas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function tampil_loker_all()
    {
        $this->db->select('pengajuan_karyawan.*,tbl_dept.*,tbl_fakultas.*,tbl_posisi.*,tbl_priority.*,tbl_tingkat_pendidikan.*,status_karyawan.*,career_posts.*')
            ->from('pengajuan_karyawan')
            ->join('tbl_dept','tbl_dept.id_dept = pengajuan_karyawan.id_dept')
            ->join('tbl_fakultas','tbl_fakultas.id_fakultas = pengajuan_karyawan.id_jurusfakult')
            ->join('tbl_posisi','tbl_posisi.id_posisi = pengajuan_karyawan.id_posisi')
            ->join('tbl_priority','tbl_priority.id_priority = pengajuan_karyawan.priority_id')
            ->join('tbl_tingkat_pendidikan','tbl_tingkat_pendidikan.id_tingkat_pendidikan = pengajuan_karyawan.id_tingkat_pendidikan')
            ->join('status_karyawan','status_karyawan.status_karyawan_id = pengajuan_karyawan.id_sk')
            ->join('career_posts','career_posts.id_careerposts = pengajuan_karyawan.id_careerposts');
        $this->db->where('pengajuan_karyawan.status_pengajuan', 'Diterima');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('pengajuan_karyawan.*,tbl_dept.*,tbl_fakultas.*,tbl_posisi.*,tbl_priority.*,tbl_tingkat_pendidikan.*,status_karyawan.*,career_posts.*')
        ->from('pengajuan_karyawan')
            ->join('tbl_dept','tbl_dept.id_dept = pengajuan_karyawan.id_dept')
            ->join('tbl_fakultas','tbl_fakultas.id_fakultas = pengajuan_karyawan.id_jurusfakult')
            ->join('tbl_posisi','tbl_posisi.id_posisi = pengajuan_karyawan.id_posisi')
            ->join('tbl_priority','tbl_priority.id_priority = pengajuan_karyawan.priority_id')
            ->join('tbl_tingkat_pendidikan','tbl_tingkat_pendidikan.id_tingkat_pendidikan = pengajuan_karyawan.id_tingkat_pendidikan')
            ->join('status_karyawan','status_karyawan.status_karyawan_id = pengajuan_karyawan.id_sk')
            ->join('career_posts','career_posts.id_careerposts = pengajuan_karyawan.id_careerposts');
        $this->db->where('pengajuan_karyawan.id_careerposts', $id);
        $query = $this->db->get();
        return $query->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_fakultas', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_fakultas', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function insert($table,$data)
    {
        $this->db->insert($table, $data);
    }

}

/* End of file Fakultas_model.php */
/* Location: ./application/models/Fakultas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-08 10:55:40 */
/* http://harviacode.com */