<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Career_posts_model extends CI_Model
{

    public $table = 'career_posts';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pengajuan_karyawan.*,career_posts.*');
        $this->datatables->from('career_posts');

        //add this line for join
        $this->datatables->join('pengajuan_karyawan', 'pengajuan_karyawan.id_careerposts = career_posts.id_careerposts');
        $this->datatables->where('pengajuan_karyawan.status_pengajuan','Diterima');
        $this->datatables->add_column('action', anchor(site_url('career_posts/read/$1'),'Pratinjau')." | ".anchor(site_url('career_posts/update/$1'),'Update')." | ".anchor(site_url('career_posts/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_careerposts', $q);
	$this->db->or_like('posts', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tgl_posts', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_careerposts', $q);
	$this->db->or_like('posts', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tgl_posts', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function updatepoststatus($id, $data) {
        $this->db->where('id_careerposts', $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Career_posts_model.php */
/* Location: ./application/models/Career_posts_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-29 06:17:10 */
/* http://harviacode.com */