<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_pelamar_model extends CI_Model
{

    public $table = 'tbl_pelamar';
    public $id = 'id_pelamar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pelamar,nama_pelamar,no_telp,email,file_suratlamaran,file_daftarriwayathidup,file_photo,file_skck,file_ktp,file_aktekelahiran,file_kk,file_ijazah,file_transkripnilai,file_npwp,file_hasilkesehatan,id_careerposts,tanggal_melamar,posisi_dilamar');
        $this->datatables->from('tbl_pelamar');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_pelamar.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_pelamar/read/$1'),'Read')." | ".anchor(site_url('data_pelamar/update/$1'),'Update')." | ".anchor(site_url('data_pelamar/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pelamar');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pelamar', $q);
	$this->db->or_like('nama_pelamar', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('file_suratlamaran', $q);
	$this->db->or_like('file_daftarriwayathidup', $q);
	$this->db->or_like('file_photo', $q);
	$this->db->or_like('file_skck', $q);
	$this->db->or_like('file_ktp', $q);
	$this->db->or_like('file_aktekelahiran', $q);
	$this->db->or_like('file_kk', $q);
	$this->db->or_like('file_ijazah', $q);
	$this->db->or_like('file_transkripnilai', $q);
	$this->db->or_like('file_npwp', $q);
	$this->db->or_like('file_hasilkesehatan', $q);
	$this->db->or_like('id_careerposts', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pelamar', $q);
	$this->db->or_like('nama_pelamar', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('file_suratlamaran', $q);
	$this->db->or_like('file_daftarriwayathidup', $q);
	$this->db->or_like('file_photo', $q);
	$this->db->or_like('file_skck', $q);
	$this->db->or_like('file_ktp', $q);
	$this->db->or_like('file_aktekelahiran', $q);
	$this->db->or_like('file_kk', $q);
	$this->db->or_like('file_ijazah', $q);
	$this->db->or_like('file_transkripnilai', $q);
	$this->db->or_like('file_npwp', $q);
	$this->db->or_like('file_hasilkesehatan', $q);
	$this->db->or_like('id_careerposts', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_pelamar_model.php */
/* Location: ./application/models/Data_pelamar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-01 01:13:33 */
/* http://harviacode.com */